services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    expose:
      - "8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app/server
      - media_volume:/app/server/media
      - static_volume:/app/server/static
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    expose:
      - "5432"
    env_file:
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  media_volume:
  static_volume:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
