services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./apps/web/.env
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app/server
      - media_volume:/app/server/media
      - static_volume:/app/server/static
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432"
    env_file:
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  media_volume:
  static_volume:

networks:
  app-network:
    driver: bridge
