services:
  db:
    image: postgres:17-alpine
    expose:
      - "5432"
    env_file:
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    expose:
      - "8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app/server
      - media_volume:/app/server/media
      - staticfiles_volume:/app/server/staticfiles
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - staticfiles_volume:/app/server/staticfiles
      - media_volume:/app/server/media
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres_data:
  media_volume:
  staticfiles_volume:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge
