# Generated by Django 5.2 on 2025-05-02 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="month_days",
            field=models.JSONField(
                default=[
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                ],
                help_text="Comma-separated list of days in month",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="weekdays",
            field=models.JSONField(
                default=[0, 1, 2, 3, 4, 5, 6],
                help_text="Comma-separated list of weekdays (0-6)",
            ),
        ),
        migrations.CreateModel(
            name="HabitReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.TimeField()),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="app.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
