# Generated by Django 5.2 on 2025-05-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_habit_month_days_alter_habit_weekdays_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitcompletion",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
